"""
Django settings for ctdjango project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os, json

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*#!cxopnjpw!b0v&x#f!%l83zeo(^b(#8*i5om_kki&)vwf=5='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'linkedct',
    'databrowse',
    'pagination',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'ctdjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ctdjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
    }
}
# Load MySQL connection info from a separate file to avoid 
# storing password in Git
with open(os.path.join(BASE_DIR, 'mysql.json')) as f:
    DATABASES['default'].update(json.load(f))


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


HOME_CONFIG = {
    'HOME': 'http://server.name/linkedct',
    'ROOT': '/linkedct/resource/',
    'RDF_ROOT': '/data/',
    'MEDIAROOT': '/home/user/workspace/linkedct/trunk/ctdjango/linkedct/static/',
    'XML_SIZE_LIMIT': 500 * 1024,  # in KB
    'D2R_SERVER': 'http://localhost:2020/',
    'D2RMAP': '@prefix map:     <file:/home/user/workspace/linkedct/d2r-server/d2r-server-0.7/initial-linkedct-live.n3#> .\n',
    'RECOVER_LOC': os.path.join(BASE_DIR, 'cache/list.txt'),
    'SOURCES_FILE_LOC': os.path.join(BASE_DIR, 'cache/'),
    'AWS_ACCESS_KEY': '',
    'AWS_SECRET_KEY': '',
    'BUCKET_NAME': '25048f14379dfe2191d7f606ee62fb2c',
    'URL_BACKUP_KEY': 'URL_BAK',
}

SERVER_CONFIG = {
    'HOME': 'http://data.linkedct.org',
    'ROOT': '/resource/',
    'RDF_ROOT': '/data/',
    'MEDIAROOT': '/root/linkedct/media',
    #'ROOT': '/resource/',
    'XML_SIZE_LIMIT': 500 * 1024,  # in KB
    'D2R_SERVER': 'http://localhost:2020/',
    'D2RMAP': '@prefix map:     <file:/root/linkedct/d2r-server/d2r-server-0.7/initial-linkedct-live.n3#> .\n',
    'RECOVER_LOC': os.path.join(BASE_DIR, 'cache/list.txt'),
    'SOURCES_FILE_LOC': os.path.join(BASE_DIR, 'cache/'),
    'AWS_ACCESS_KEY': '',
    'AWS_SECRET_KEY': '',
    'BUCKET_NAME': '25048f14379dfe2191d7f606ee62fb2c',
    'URL_BACKUP_KEY': 'URL_BAK',
}

CS_CONFIG = {
#    'HOME': 'http://www.cs.toronto.edu:40104',
    'HOME': 'http://data.linkedct.org',
    'ROOT': '/resource/',
    'RDF_ROOT': '/data/',
    'MEDIAROOT': '/root/linkedct/media',
    #'ROOT': '/resource/',
    'XML_SIZE_LIMIT': 500 * 1024,  # in KB
    'D2R_SERVER': 'http://localhost:40116/',
    'D2RMAP': '    xmlns:map="file:/home/user/workspace/linkedct/d2r-server/d2r-server-0.7/initial-linkedct-live.n3#"\n',
    'RECOVER_LOC': os.path.join(BASE_DIR, 'cache/list.txt'),
    'SOURCES_FILE_LOC': os.path.join(BASE_DIR, 'cache/'),
    'AWS_ACCESS_KEY': '',
    'AWS_SECRET_KEY': '',
    'BUCKET_NAME': '25048f14379dfe2191d7f606ee62fb2c',
    'URL_BACKUP_KEY': 'URL_BAK',
}

CONFIG = CS_CONFIG

PAGINATION_INVALID_PAGE_RAISES_404 = True

CACHE_MIDDLEWARE_SECONDS = 100000 
CACHE_MIDDLEWARE_KEY_PREFIX = 'ctdjango'
#CACHE_BACKEND = 'memcached://127.0.0.1:11211/'
CACHE_BACKEND = 'file:///u/user/tmp/django_cache'

SITE_ID = 0 
